FROM registry.redhat.io/ubi9/ubi-minimal:latest

ENV LANGUAGE='en_US:en'

COPY --chown=185 target/*.jar /deployments/

EXPOSE 8080
USER 185
ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"
ENV JAVA_APP_JAR="/deployments/quarkus-run.jar"

ENTRYPOINT [ "/opt/jboss/container/java/run/run-java.sh" ]

