---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-config
  labels:
    app: mongodb
data:
  MONGODB_ROOT_USER: user
  MONGODB_ROOT_PASSWORD: pass
  MONGODB_REPLICA_SET_MODE: primary
  MONGODB_REPLICA_SET_NAME: rs0
  MONGODB_REPLICA_SET_KEY: replicakey123456
  MONGODB_DATABASE: db
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
    name: mongodb
    protocol: TCP
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: docker.io/bitnami/mongodb:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 50m
              memory: 64Mi
          ports:
            - containerPort: 27017
              name: mongodb
              protocol: TCP
          envFrom:
            - configMapRef:
                name: mongodb-config
          volumeMounts:
            - mountPath: /bitnami
              name: mongodbdata
      volumes:
        - name: mongodbdata
          emptyDir: {}
