# Use Red Hat Universal Base Image 9 Minimal as the base image
FROM redhat/ubi9-minimal

# Set the default command to print "Hello World ssf" when container starts
ENTRYPOINT [ "echo", "Hello World!" ] 