apiVersion: org.eclipse.che/v2
kind: CheCluster
metadata:
  name: devspaces
spec:
  devEnvironments:
    containerBuildConfiguration:
      openShiftSecurityContextConstraint: nested-podman-scc
    disableContainerBuildCapabilities: false
    defaultComponents:
      - attributes:
          pod-overrides:
            metadata:
              annotations:
                io.kubernetes.cri-o.Devices: /dev/fuse,/dev/net/tun
            spec:
              hostUsers: false
          container-overrides:
              securityContext:
                procMount: Unmasked
        container:
          image: quay.io/mmascia/universal-developer-image:3.19
          sourceMapping: /projects
          env:
            - name: KUBEDOCK_ENABLED
              value: 'false'
            - name: PULL_POLICY
              value: always
            - name: INIT_IMAGE
              value: docker.io/joyrex2001/kubedock:0.18.1
            - name: KUBEDOCK_TIMEOUT
              value: '120'
            - name: KUBECONFIG
              value: /home/user/.kube/config
            - name: DOCKER_HOST
              value: tcp://127.0.0.1:2475
            - name: SSL_CERT_DIR
              value: /var/run/secrets/kubernetes.io/serviceaccount
        name: developer-image
    workspacesPodAnnotations:
      io.kubernetes.cri-o.Devices: /dev/fuse,/dev/net/tun