kind: ConfigMap
apiVersion: v1
metadata:
  name: user-config
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-configmap: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /home/user
data:
  .npmrc: |
    proxy=http://user:passsword@host.domain.com:8080/
    https-proxy=http://user:passsword@host.domain.com:8080/
    strict-ssl=false
    registry=http://registry.npmjs.org/
    cache=/home/user/.npm/caches/npm-cache
    prefix=/home/user/.npm/caches/npm
  .bashrc: |
    # Bash config