[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore specific user config
    '''\.deprecated\/nodejs\/userconfig\/configmap\.yaml$''',
  ]