---
apiVersion: v1
kind: Pod
metadata:
  name: python-server-second
  labels:
    app: python-server-second
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: python-server-container
    image: registry.redhat.io/ubi9/python-312
    ports:
    - containerPort: 8000
    command: ["python3", "-m", "http.server"]
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.2"
        memory: "256Mi"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: ["ALL"]
      readOnlyRootFilesystem: true
    livenessProbe:
      httpGet:
        path: /
        port: 8000
      initialDelaySeconds: 3
      periodSeconds: 3