FROM nginx:1.16.0
   
# Create required directories and set permissions
RUN mkdir -p /var/cache/nginx /var/run && \
    chown 0:0 /var/cache/nginx /var/run && \
    chmod -R g=u /var/cache/nginx /var/run
    
# Copy nginx.conf
COPY --chown=0:0 nginx.conf /etc/nginx/nginx.conf

# Use arbitrary user ID as per OpenShift guidelines
USER 1001