{{- if .Values.vllm.enabled }}
---
{{- if .Values.vllm.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai.serviceAccountName" . }}-vllm
  labels:
    {{- include "ai.labels" . | nindent 4 }}
  {{- with .Values.vllm.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.vllm.serviceAccount.automount }}
{{- end }}
{{- end }}
