---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai.fullname" . }}-vllm
  labels:
    {{- include "ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  HUGGING_FACE_HUB_TOKEN: "t0p-s3cr3t"
