{{- if .Values.vllm.enabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai.fullname" . }}-vllm-data
  labels:
    {{- include "ai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.vllm.storage.size }}
{{- end }}