{{- if eq .Values.aiType "ollama" }}
{{- if .Values.ollama.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai.serviceAccountName" (merge . (dict "aiType" "ollama")) }}-ollama
  labels:
    {{- include "ai.labels" . | nindent 4 }}
  {{- with .Values.ollama.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ollama.serviceAccount.automount }}
{{- end }}
{{- end }}
