apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai.fullname" . }}-ollama
  labels:
    {{- include "ai.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ollama
      protocol: TCP
      name: ollama
  selector:
    {{- include "ai.selectorLabels" . | nindent 4 }}
