---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: yq
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Build Tools
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "tag"
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  workspaces:
    - name: source
  params:
    - name: commands
      type: string
      description: The set of commands to run
  steps:
    - name: yq
      workingDir: $(workspaces.source.path)
      image: mikefarah/yq:4
      script: |
        #!/usr/bin/env sh
        set -x
        $(params.commands)