
quarkus.openshift.route.expose=true

quarkus.kubernetes.idempotent=true

quarkus.container-image.registry=image-registry.openshift-image-registry.svc:5000
quarkus.container-image.group=${WORKSPACE_NAMESPACE}