apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: angular-app
spec:
  destination:
    name: ''
    namespace: devspaces-admin
    server: 'https://kubernetes.default.svc'
  source:
    path: js/frontend/helm
    repoURL: 'https://github.com/openlab-red/openshift-quickstart-manifest'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-devspaces-admin.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
