apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: java-webhook
spec:
  params:
    - default: master
      description: The git revision
      name: git-revision
    - description: The git repository url
      name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: java-pipeline-webhook-
        labels:
          tekton.dev/pipeline: java-pipeline
      spec:
        params:
          - name: deployment-name
            value: openshift-quickstart
          - name: git-url
            value: 'https://github.com/openlab-red/openshift-quickstart/'
          - name: git-revision
            value: main
          - name: IMAGE
            value: quay.io/pod-play/openshift-quickstart
          - name: CONTEXT_DIR
            value: java
          - name: git-manifest-url
            value: 'https://github.com/openlab-red/openshift-quickstart-manifest/'
        pipelineRef:
          name: java-pipeline
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: shared-workspace
          - name: manifest-workspace
            persistentVolumeClaim:
              claimName: manifest-workspace
