spring:
  jpa:
    database: MYSQL
  datasource:
    url: jdbc:mysql://localhost:3306/db
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration/common, classpath:db/migration/mysql