apiVersion: v1
kind: Secret
metadata:
  name: admin-devspaces-devspaces-pull-secret
  labels:
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
  annotations:
    controller.devfile.io/mount-as: subpath
    controller.devfile.io/mount-path: /home/user/.docker
data:
  config.json: xxx==
type: Opache