---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "pipeline.fullname" . }}
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
spec:
  params:
    - default: 'https://github.com/openlab-red/openshift-quickstart/'
      description: url of the git repo for the code of deployment
      name: git-url
      type: string
    - default: main
      description: revision to be used from repo of the code for deployment
      name: git-revision
      type: string
    - default: quay.io/quickstart/{{ include "pipeline.type" . }}/{{ .Values.appName }}
      description: image to be build from the code
      name: IMAGE
      type: string
    - default: tutorials/{{ include "pipeline.type" . }}/{{ .Values.subPath }}
      description: context dir
      name: CONTEXT_DIR
      type: string
    - default: Containerfile
      description: Containerfile
      name: CONTAINER_FILE
      type: string
    - default: 'https://github.com/openlab-red/openshift-quickstart-manifest/'
      description: url of the git manifest repo
      name: git-manifest-url
      type: string
  tasks:
  
    - name: fetch-repository
      params:
        - name: URL
          value: $(params.git-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: git-clone
        - name: namespace
          value: openshift-pipelines
      workspaces:
        - name: output
          workspace: {{ include "pipeline.fullname" . }}-ws


    - name: tag
      runAfter:
        - fetch-repository
      params:
        - name: prefix
          value: {{ .Release.Namespace }}
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: gen-tag
        - name: namespace
          value: openshift-pipelines

{{- if contains "java" .Release.Name }}
    {{ include "pipeline.java-build" . }}
{{- end }}

{{- if contains "golang" .Release.Name }}
    {{ include "pipeline.golang-build" . }}
{{- end }}

{{- if contains "js" .Release.Name }}
    {{ include "pipeline.js-build" . }}
{{- end }}

    - name: build-image
      params:
        - name: IMAGE
          value: 'quay.io/quickstart/{{ include "pipeline.type" . }}/{{ .Values.appName }}:s-$(tasks.tag.results.tag)'
        - name: CONTEXT
          value: $(params.CONTEXT_DIR)
        - name: DOCKERFILE
          value: $(params.CONTAINER_FILE)
        - name: TLSVERIFY
          value: 'false'
      runAfter:
        - build-app
        - tag
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: buildah
        - name: namespace
          value: openshift-pipelines
      workspaces:
        - name: source
          workspace: {{ include "pipeline.fullname" . }}-ws
        - name: dockerconfig
          workspace: {{ include "pipeline.fullname" . }}-dockerconfig


    - name: publish
      params:
        - name: SOURCE_IMAGE_URL
          value: 'docker://quay.io/quickstart/{{ include "pipeline.type" . }}/{{ .Values.appName }}:s-$(tasks.tag.results.tag)'
        - name: DESTINATION_IMAGE_URL
          value: >-
            docker://quay.io/quickstart/{{ include "pipeline.type" . }}/{{ .Values.appName }}:$(tasks.tag.results.tag)
      runAfter:
        - build-image
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: skopeo-copy
        - name: namespace
          value: openshift-pipelines
      workspaces:
        - name: images_url
          workspace: {{ include "pipeline.fullname" . }}-ws


    - name: fetch-manifest
      params:
        - name: URL
          value: $(params.git-manifest-url)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
        - name: revision
          value: $(params.git-revision)
      runAfter:
        - publish
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: git-clone
        - name: namespace
          value: openshift-pipelines
      workspaces:
        - name: output
          workspace: {{ include "pipeline.fullname" . }}-resource-ws


    - name: update-manifest
      params:
        - name: commands
          value: |
            CONTEXT_PATH={{ include "pipeline.type" . }}{{ if .Values.manifestPath }}/{{ .Values.manifestPath }}{{ end }} && \
            VALUES_FILE=$CONTEXT_PATH/helm/values-{{ .Release.Namespace }}.yaml && \
            touch $VALUES_FILE && \
            yq eval '.image.repository = "quay.io/quickstart/{{ include "pipeline.type" . }}/{{ .Values.appName }}"' $VALUES_FILE -i && \
            yq eval '.image.tag = "$(tasks.tag.results.tag)"' $VALUES_FILE -i
      runAfter:
        - fetch-manifest
      taskRef:
        resolver: cluster
        params:
        - name: kind
          value: task
        - name: name
          value: yq
        - name: namespace
          value: openshift-pipelines
      workspaces:
        - name: source
          workspace: {{ include "pipeline.fullname" . }}-resource-ws


    - name: update-gitops
      params:
        - name: git_revision
          value: main
        - name: image
          value: 'quay.io/quickstart/{{ include "pipeline.type" . }}/{{ .Values.appName }}:$(tasks.tag.results.tag)'
        - name: push_retry_count
          value: '3'
      runAfter:
        - update-manifest
      taskRef:
        resolver: cluster
        params:
          - name: kind
            value: task
          - name: name
            value: update-gitops
          - name: namespace
            value: openshift-pipelines
      workspaces:
        - name: source
          workspace: {{ include "pipeline.fullname" . }}-resource-ws
        - name: git-credentials
          workspace: {{ include "pipeline.fullname" . }}-git-credentials

  workspaces:
    - name: {{ include "pipeline.fullname" . }}-ws
    - name: {{ include "pipeline.fullname" . }}-resource-ws
    - name: {{ include "pipeline.fullname" . }}-dockerconfig
    - name: {{ include "pipeline.fullname" . }}-git-credentials