apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pipeline.fullname" . }}-ws
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pipeline.fullname" . }}-resource-ws
  labels:
    {{- include "pipeline.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi