apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

components:
- ../components/featuregate
- ../components/containerruntime
- ../components/operators/imageregistry
- ../components/operators/devspaces
- ../components/operators/devworkspaces
- ../components/operators/kubernetes-imagepuller
- ../components/operators/pipeline
- ../components/operators/gitops
- ../components/scc/nested-container


resources: []