apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
- ../components/featuregate
- ../components/operators/devspaces
- ../components/operators/devworkspaces
- ../components/operators/kubernetes-imagepuller
- ../components/scc/nested-container

resources: []