apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators

components:
- ../components/featuregate
- ../components/containerruntime
- ../components/operators/devspaces
- ../components/operators/devworkspaces
- ../components/operators/kubernetes-imagepuller
- ../components/scc/nested-container
- ../components/scc/pipeline
- ../components/scc/gitops

resources: []