apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations: {}
  
resources:
- devspaces-checluster.yaml
# - devworkspaceoperatorconfig.yaml
#- getting-started-samples.yaml
- servicemonitor.yaml
- devspaces-hpa.yaml
- devspaces-dashboard-hpa.yaml
- che-gateway-hpa.yaml

replacements: []

patches: []

# configMapGenerator:
# - name: custom-ca-bundle
#   files:
#   - ca.crt=certs/ca-bundle.crt
#   options:
#     disableNameSuffixHash: true
#     annotations:
#       argocd.argoproj.io/compare-options: IgnoreExtraneous
#       argocd.argoproj.io/sync-options: Prune=false
#     labels:
#       app.kubernetes.io/component: ca-bundle
#       app.kubernetes.io/part-of: che.eclipse.org
#       controller.devfile.io/watch-configmap: 'true'

# secretGenerator:
# - name: devspaces-dashboard-customization
#   files:
#   - loader.svg=svg/logo.svg
#   options:
#     disableNameSuffixHash: true
#     annotations:
#       argocd.argoproj.io/compare-options: IgnoreExtraneous
#       argocd.argoproj.io/sync-options: Prune=false
#       che.eclipse.org/mount-as: subpath
#       che.eclipse.org/mount-path: /public/dashboard/assets/branding
#     labels:
#       app.kubernetes.io/component: devspaces-dashboard-secret
#       app.kubernetes.io/part-of: che.eclipse.org