apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devworkspace-controller
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 10s 
      port: metrics
      scheme: https
      tlsConfig:
        ca: 
          configMap:
            name: kube-root-ca.crt
            key: ca.crt
  namespaceSelector:
    matchNames:
      - openshift-operators
  selector:
    matchLabels:
      app.kubernetes.io/name: devworkspace-controller
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: che-host
spec:
  endpoints:
    - interval: 10s 
      port: metrics
      scheme: http
  namespaceSelector:
    matchNames:
      - openshift-operators 
  selector:
    matchLabels:
      app.kubernetes.io/name: devspaces