---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai.fullname" . }}-data
  labels:
    {{- include "ai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai.fullname" . }}-static
  labels:
    {{- include "ai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
