---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "ai.fullname" . }}-openweb
  labels:
    {{- include "ai.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "ai.fullname" . }}-openweb
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
