apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-pipelines

resources:
- resources/go-build.yaml
- resources/helm.yaml
- resources/tag.yaml
- resources/update-gitops.yaml
- resources/yq.yaml