apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "myapp.fullname" . }}-nginx-config
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
data:
  nginx.conf: |
{{ .Files.Get "nginx.conf" | indent 4 }}
