---
{{- if eq .Values.aiType "ramalama" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "ai.fullname" . }}-ramalama-data
  labels:
    {{- include "ai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.ramalama.storage.size }}
{{- end }}
