{{- if eq .Values.aiType "ramalama" }}
{{- if .Values.ramalama.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai.serviceAccountName" (merge . (dict "aiType" "ramalama")) }}-ramalama
  labels:
    {{- include "ai.labels" . | nindent 4 }}
  {{- with .Values.ramalama.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.ramalama.serviceAccount.automount }}
{{- end }}
{{- end }}
