apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./charts
helmCharts:
  - name: myapp
    releaseName: prod
    namespace: prod
    valuesInline:
      replicaCount: 2

patches:
  - path: deployment-patch.yaml