apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ./charts
helmCharts:
  - name: myapp
    releaseName: myapp-prod
    namespace: prod
    valuesInline:
      replicaCount: 2
