nav:
  - index.md
  - tutorials/simple/index.md
  - Simple Pod: tutorials/python/index.md
  - tutorials/rbac/index.md
  - tutorials/networkpolicy/index.md
  - tutorials/helm+kustomize/index.md
  - NodeJS: tutorials/js/index.md
  - GoLang: tutorials/golang/index.md
  - Java:
    - tutorials/java/index.md
    - tutorials/java/helloworld/index.md
    - tutorials/java/quarkus/index.md
    - tutorials/java/springboot/index.md
  - Pipeline: tutorials/pipeline/index.md