nav:
  - index.md
  - tutorials/simple/index.md
  - Simple Pod: tutorials/python/index.md
  - tutorials/rbac/index.md
  - tutorials/networkpolicy/index.md
  - tutorials/helm+kustomize/index.md
  - NodeJS: tutorials/js/index.md
  - GoLang: tutorials/golang/index.md
  - Java:
    - Java Overview: tutorials/java/index.md
    - Quarkus: tutorials/java/quarkus/index.md
    - Spring Boot: tutorials/java/springboot/index.md
  - GitOps:
    - Pipeline: tutorials/gitops/pipeline/index.md
    - ArgoCD: tutorials/gitops/argocd/index.md
  - AI: tutorials/ai/index.md