apiVersion: controller.devfile.io/v1alpha1
kind: DevWorkspaceOperatorConfig
metadata:
  name: devworkspace-operator-config
  labels:
    controller.devfile.io/watch-configmap: 'true'
config:
  routing:
    tlsCertificateConfigmapRef:
      name: ca-bundle
