---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai.fullname" . }}-openweb
  labels:
    {{- include "ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  OLLAMA_BASE_URL: http://{{ include "ai.fullname" . }}-ollama:{{ .Values.service.port }}
  WEBUI_SECRET_KEY: "t0p-s3cr3t"
