apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai.fullname" . }}-openweb
  labels:
    {{- include "ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  WEBUI_SECRET_KEY: "t0p-s3cr3t"
  {{- if eq .Values.aiType "ollama" }}
  OLLAMA_BASE_URL: http://{{ include "ai.fullname" . }}-ollama.{{.Release.Namespace}}.svc:{{ .Values.ollama.service.port }}
  {{- else if eq .Values.aiType "ramalama" }}
  OPENAI_API_BASE_URL:  http://{{ include "ai.fullname" . }}-ramalama.{{.Release.Namespace}}.svc:{{ .Values.ramalama.service.port }}
  {{- else if eq .Values.aiType "vllm" }}
  OPENAI_API_BASE_URL: http://{{ include "ai.fullname" . }}-vllm.{{.Release.Namespace}}.svc:{{ .Values.vllm.service.port }}/v1
  {{- end }}
