{{- if .Values.openweb.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ai.openwebServiceAccountName" . }}-openweb
  labels:
    {{- include "ai.labels" . | nindent 4 }}
  {{- with .Values.openweb.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.openweb.serviceAccount.automount }}
{{- end }}
