apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-communication
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: openshift-quickstart
  policyTypes:
  - Ingress
