apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-k
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-k
  template:
    metadata:
      labels:
        app: myapp-k
    spec:
      containers:
      - name: nginx
        image: registry.redhat.io/ubi9/nginx-122:latest
        command: ["nginx"]
        args: ["-g", "daemon off;"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "200m" 
            memory: "128Mi"