
quarkus.openshift.route.expose=true

quarkus.kubernetes-client.trust-certs=true
quarkus.kubernetes.idempotent=true

quarkus.container-image.registry=quay.io
quarkus.container-image.group=${WORKSPACE_NAMESPACE}


quarkus.openshift.image-push-secret=${WORKSPACE_NAMESPACE}-openshift-push-secret
quarkus.openshift.deployment-kind=Deployment